# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42e8ed2150041d1c17b4d07911f4febe8772e9cdbbe0cfc8418eeec916f3b425c84cdfd910e8dee46a4691a3f6d9c7dfa5bf365fc45382ef8c937dc007759a8f

test:
  secret_key_base: 3ccd0d95e0286cc4c01cae8f076a282f79d7adbf238a6ea4c8cbab12926b5ac3a9f2ac0c87178b16aea3588768bed659d9613705f07976023d9f50b65a61c99f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 3ccd0d95e0286cc4c01cae8f076a282f79d7adbf238a6ea4c8cbab12926b5ac3a9f2ac0c87178b16aea3588768bed659d9613705f07976023d9f50b65a61c99f
